apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-manual
  namespace: hw-kube-stor
spec:
  volumeName: pv-local-manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
